# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods
  pod 'PinLayout', '~> 1.8.7'
  pod 'SnapKit'
  pod 'Kingfisher', '~> 5.7.1'
  pod 'IQKeyboardManagerSwift', ' ~> 6.3.0'
  pod 'Moya'
  pod 'PromisesSwift'
  
  # Security
  pod 'KeychainAccess'
end

def analitycs
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
  pod 'Firebase/Analytics'
end

def interface
  pod 'SegementSlide', '~> 2.2.1'
  pod 'JTAppleCalendar'
  pod 'YPImagePicker', `~> 4.2.1`
end

target 'HabitTracker' do
  use_frameworks!

  common_pods
  analitycs
  interface
  
end

target 'HabitTrackerTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'HabitTrackerUITests' do
  # Pods for testing
end
