# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods
  pod 'PinLayout', '~> 1.8.7'
  pod 'Kingfisher', '~> 5.7.1'
  pod 'SegementSlide', '~> 2.2.1'
  pod 'SnapKit'
  pod 'IQKeyboardManagerSwift', ' ~> 6.3.0'
  pod 'JTAppleCalendar'
  pod 'Charts', '~> 3.5.0'
  pod 'YPImagePicker'
  # Google API
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
  pod 'Firebase/Analytics'
  pod 'Moya'
  pod 'PromisesSwift'
end


target 'HabitTracker' do
  use_frameworks!

  common_pods
end

target 'HabitTrackerTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'HabitTrackerUITests' do
  # Pods for testing
end
