# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!

def common_pods
  pod 'PinLayout', '~> 1.8.7'
  pod 'SnapKit'
  pod 'Kingfisher', '~> 5.7.1'
  pod 'IQKeyboardManagerSwift', '~> 6.3.0'
  pod 'Moya'
  pod 'PromisesSwift'
  pod 'CoreStore', '~> 7.2'
  
  # Security
  pod 'KeychainAccess'
end

def analitycs
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
  pod 'Firebase/Analytics'
end

def interface
  pod 'SegementSlide', '~> 2.2.1'
  pod 'JTAppleCalendar'
  pod 'YPImagePicker'
end

target 'HabitTracker' do
  use_frameworks!

  common_pods
  analitycs
  interface
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
